### ISSUE TITLE
Performance benefits in sharing the connection?

### ISSUE THREAD

**Issue by seankearon** [aaronpowell/FSharp.CosmosDb#24]
I'm wondering whether there are any performance benefits to sharing the connection?  Something like this:

```
let host = "https://..."
let key = "..."

// Create my container once and hold it as a value.
let container =
    host
    |> Cosmos.host
    |> Cosmos.connect key
    |> Cosmos.database "UserDb"
    |> Cosmos.container |> "UserContainer"

let userByName name =
    container
    |> Cosmos.query "SELECT u.FirstName, u.LastName FROM u WHERE u.LastName = @name"
    |> Cosmos.parameters [ "name", box "Powell" ]
    |> Cosmos.execAsync<User>

let userByEmail email =
    // etc.
```

**Comment by aaronpowell** [comment]
Not really, the connection isn't established until `execAsync` is run, so all you're doing is caching the creation of the record type.

I'm also unsure on the guidance for the SDK on whether you should be caching the `CosmosClient`/`Database`/`Container` either, so I may change the way it works internally in the future.

**Comment by seankearon** [comment]
I'm also not sure of the best way to approach the creation of the parts used to connect.  So, I'll just sit and be happy while reaping the benefits of your lovely work!  Thank you, Aaron. 😄
