### ISSUE TITLE
Use a singleton Azure Cosmos DB client for the lifetime of your application

### ISSUE THREAD

**Issue by travis-leith** [aaronpowell/FSharp.CosmosDb#42]
The [official performance guidance (at least for v3 SDK)](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql#sdk-usage) is to keep a single client for the lifetime of the app.

I think this library should either implement the singleton pattern, or provide an argument to `execAsync` that takes in the client.

Unless, of course, this advice is no longer relevant for v4. I could not find a similar page for v4.

**Comment by travis-leith** [comment]
I'd like to submit a PR to address this but because of an [Ionide issue](https://github.com/ionide/FSharp.Analyzers.SDK/issues/17) you are already aware of, I cannot get it to build with the Analyzer. Perhaps this should wait until Ionide upgrade their dependencies?

**Comment by aaronpowell** [comment]
I assume it's the same guidance for v4, I've reached out to the team for clarity
