### ISSUE TITLE
Any chance of UPSERT support?

### ISSUE THREAD

**Issue by PhalanxHead** [aaronpowell/FSharp.CosmosDb#43]
Hey!
This is a really handy package, I am enjoying playing with it.
Any chance of supporting the UPSERT command from Cosmos?

My current method is to query for matching IDs and Insert the difference, but I feel like UPSERT would be more idiomatic.

Thanks!

**Comment by aaronpowell** [comment]
I've added this in https://github.com/aaronpowell/FSharp.CosmosDb/commit/0f8dd3d1954cb50faa28ecd221385af53012b34e, and will cut a new release shortly, but in the meantime you can grab the nupkg's from https://github.com/aaronpowell/FSharp.CosmosDb/runs/1508486517?check_suite_focus=true or use the `0.3.0` pre-release packages from https://github.com/aaronpowell?tab=packages&repo_name=FSharp.CosmosDb

**Comment by aaronpowell** [comment]
It's available on NuGet now.
