### ISSUE TITLE
Is Paket required for FSharp.CosmosDb.Analyzer?

### ISSUE THREAD

**Issue by mabasic** [aaronpowell/FSharp.CosmosDb#56]
I am using `dotnet add package`, but I don't have the packages directory anywhere.

**Comment by aaronpowell** [comment]
You don't need to use paket for the analyzer, it's just the easiest way to control install locations, as you need to provide a path to the analyzer for Ionide to get it from.

**Comment by mabasic** [comment]
Do you know how can I install the package and tell Ionide its location by using dotnet and not paket?

I'm new to the .NET ecosystem..

**Comment by aaronpowell** [comment]
You can use the [`--package-directory` flag on the `dotnet add package` command](https://docs.microsoft.com/dotnet/core/tools/dotnet-add-package?WT.mc_id=javascript-0000-aapowell).

**Comment by mabasic** [comment]
I am using:

```
dotnet add package FSharp.CosmosDb.Analyzer --package-directory ./packages
```

This create a new directory called `packages` and inside it places a whole bunch of things. I assume that I need to add this directory to gitignore?

**Comment by mabasic** [comment]
I have tried everything that came to mind, read all the blog posts and still I can't get this to work.

How do I know if the analyzer is picked up in ionide?

Is this related to: https://github.com/ionide/FSharp.Analyzers.SDK/issues/9

**Comment by aaronpowell** [comment]
I'll admit to never having tried with NuGet so it may be related to that problem.

From my understanding of how analyzers work, they require the path to the folder the DLL is in, and for it to be there when the Ionide plugin starts up, so it can load.

If you look into the Ionide logs in VS Code you might get some insights

**Comment by aaronpowell** [comment]
In the VS Code output pane there's a drop down list with all the different output logs. Ionide appears as F# _something_
