### ISSUE TITLE
Does it support Stored Procedure?

### ISSUE THREAD

**Issue by mastoj** [aaronpowell/FSharp.CosmosDb#59]
Nice work with the library!

Is it possible to execute stored procedure with it somehow? Like with using the query or something?

**Comment by aaronpowell** [comment]
I didn't even know that Cosmos had Stored Procedures... so right now, there's no specific API that would allow it.

In v1 I've added a `Raw` module that will allow you to get the container and then from there you could execute the stored procedure.

But if you're willing to write up how you'd envisage an API that would allow you to call a stored procedure, I'll see if I can get it into v1.

**Comment by mastoj** [comment]
I haven't thought that much about it, and I don't think I would be the best person to define it either I'm afraid... I only did a one time job and doesn't write too much code against cosmos db I'm afraid.

I worked my way around it and created a new connection and used the stored proc from there. Maybe that could be made simpler and exposed in the API, that is, expose the connection to give access to the SDK functionality. Maybe that is what you mean with the `Raw` part.

**Comment by aaronpowell** [comment]
I've released v1.0 with support for accessing the raw client. If you have an idea of how to better support stored procedures (which aren't something I use in Cosmos), we can reopen this issue to come up with a better programming model.
