### ISSUE TITLE
[Request] Make compatable with newer Azure Functions versions

### ISSUE THREAD

**Issue by osheari1** [aaronpowell/FSharp.CosmosDb#63]
Currently the most recent functions versions require .NET Core 6.0, but the currently implementation is pinned to .NET Framework 4.0.

**Comment by aaronpowell** [comment]
Azure Functions [supports .NET 6](https://docs.microsoft.com/azure/azure-functions/create-first-function-vs-code-csharp?tabs=in-process&WT.mc_id=javascript-0000-aapowell) which is compatible with this package.

There's no plan to support lower versions of .NET.
