### ISSUE TITLE
Replace doesn't resolve correct id value

### ISSUE THREAD

**Issue by mickednk** [aaronpowell/FSharp.CosmosDb#69]
When doing a replace of an item the value "id" is resolved instead of the value of the property "id" if you haven't added an IdAttribute on the id property.

I think this is where the issue lies.
```
let getIdFieldName<'T> (item: 'T) =
    let idAttr = IdAttributeTools.findId<'T> ()

    match idAttr with
    | Some attr -> attr.GetValue(item).ToString()
    | None -> "id"
```

**Comment by aaronpowell** [comment]
Ha, yeah that's probably true.

I guess I need better test coverage 🤣

**Comment by aaronpowell** [comment]
Got around to patching this, you'll find a build available here: https://github.com/aaronpowell/FSharp.CosmosDb/packages/530463?version=1.2.1-ci-3261757948

Can you verify @mickednk before I merge it?

**Comment by mickednk** [comment]
It works for me.
